Fix Traceback on results update in reference laboratory
```
Traceback (most recent call last):
  File "/home/senaite/buildout-cache/eggs/plone.jsonapi.core-0.7.0-py2.7.egg/plone/jsonapi/core/browser/decorators.py", line 23, in decorator
    return f(*args, **kwargs)
  File "/home/senaite/buildout-cache/eggs/plone.jsonapi.core-0.7.0-py2.7.egg/plone/jsonapi/core/browser/api.py", line 57, in to_json
    return self.dispatch()
  File "/home/senaite/buildout-cache/eggs/plone.jsonapi.core-0.7.0-py2.7.egg/plone/jsonapi/core/browser/api.py", line 51, in dispatch
    return router(self.context, self.request, path)
  File "/home/senaite/buildout-cache/eggs/plone.jsonapi.core-0.7.0-py2.7.egg/plone/jsonapi/core/browser/router.py", line 150, in __call__
    return self.view_functions[endpoint](context, request, **values)
  File "/home/senaite/senaite/src/senaite.jsonapi/src/senaite/jsonapi/v1/routes/push.py", line 61, in push
    api.fail(500, str(e))
  File "/home/senaite/senaite/src/senaite.jsonapi/src/senaite/jsonapi/api.py", line 583, in fail
    raise APIError(status, "{}".format(msg))
APIError: 'ascii' codec can't encode character u'\u2076' in position 7: ordinal not in range(128)
```